# Generated by Django 5.2.1 on 2025-12-30 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0004_payment_created_by_payment_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('M-Pesa', 'M-Pesa'), ('Airtel Money', 'Airtel Money'), ('YAS', 'YAS'), ('Halopesa', 'Halopesa'), ('Bank Transfer', 'Bank Transfer'), ('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Other', 'Other')], default='M-Pesa', max_length=50),
        ),
    ]
