# Generated by Django 5.2.1 on 2025-12-30 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0005_alter_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Other', 'Other')], default='M-Pesa', max_length=50),
        ),
    ]
