# Generated by Django 5.2.9 on 2026-01-01 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0007_merge'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Document', 'verbose_name_plural': 'Payments'},
        ),
    ]
