# Generated by Django 5.2.1 on 2026-01-04 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0008_alter_document_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenancy',
            old_name='end_date',
            new_name='last_payment_date',
        ),
        migrations.AddField(
            model_name='tenancy',
            name='months_paid',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
